// The manual's words (app/manual.tsx): every function the app has, part by part as the app is laid out, each with
// where it is (the taps, in order, as the buttons read) and what it does, in plain words. Only what is live: a new
// function adds its line here. Checked by `npm test` (lib/manual.test.mjs): every page a line opens exists.

export type ManualItem = {
  name: string; // what you'd look for: "Delete a run"
  where: string[]; // the taps, in order: ['Weekend', 'the event', 'Laps', 'Delete next to the run']
  what: string; // what it does, in a sentence or two
  href?: string; // a page of its own to open straight away
};

export type ManualPart = {
  key: string;
  title: string; // the part of the app: "Race weekends", "Debriefs"
  dek: string; // what the part is for
  href?: string; // its page, when it has one of its own
  items: ManualItem[];
};

export const MANUAL: ManualPart[] = [
  {
    key: 'everywhere',
    title: 'On every page',
    dek: 'The bar at the top, Back, the red Debrief key and the moves that work on any list of runs.',
    items: [
      { name: 'Go to a part of the app', where: ['Top of every page', 'Weekend, Coaching, Drivers, Setup, Upload or Tools'],
        what: 'The links under the app’s name take you to each part; the one you are in is underlined in red. “The Engineer” takes you to the race weekends.' },
      { name: 'Go back', where: ['Top of every page', '‹ Back'],
        what: 'One page back. Opened from a link, it goes up to the page above: a run to its event, a tool to Tools, everything else to the race weekends.' },
      { name: 'Record a debrief from anywhere', where: ['Bottom right of every page', 'Debrief (the red square)'],
        what: 'One tap opens Debrief and starts recording at once. The recording goes with the run that ended just before it.' },
      { name: 'Open this manual', where: ['Top of every page', 'Manual'],
        what: 'Every function and where to find it. Type a word to find one.' },
      { name: 'Print or save a page as PDF', where: ['Event, run, report, Compare laps and debrief pages', 'Print / Save as PDF'],
        what: 'Prints the page or saves it as a PDF. From the iPhone home-screen app it makes a PDF to share.' },
      { name: 'See the newest version after an update', where: ['Any page', 'Ctrl+Shift+R (Cmd+Shift+R on a Mac)'],
        what: 'A hard reload loads the app as it is now. On a phone, close the app and open it again.' },
      { name: 'Swipe or hold a run', where: ['Any list of runs', 'swipe the run left, or hold it'],
        what: 'On a phone or tablet, swipe a run left for Delete. Hold any run for Delete, Change driver, Rename and Tyres. Every one of these also has a button you can see.' },
      { name: 'What opens when you start the app', where: ['Starting the app'],
        what: 'On a phone it opens on Debrief, ready to record. On a computer it opens on the event that is on now (from the day before it), or one starting within 14 days.' },
    ],
  },
  {
    key: 'weekends',
    title: 'Race weekends',
    dek: 'The list of events, by year and championship, each with its runs.',
    href: '/',
    items: [
      { name: 'Find an event', where: ['Weekend', 'Past, Current, Upcoming or All'],
        what: 'Picks which events are listed. They are grouped by year, then by championship; tap a heading to fold it.' },
      { name: 'Open an event', where: ['Weekend', 'tap the event'],
        what: 'Opens its weekend page: Laps, Before, During and After.' },
      { name: 'See an event’s runs in the list', where: ['Weekend', '▸ beside the event'],
        what: 'Shows its runs day by day with each run’s best lap and its gap to the event’s best, then the event’s best lap, clean laps and track.' },
      { name: 'Rename a run', where: ['Weekend', '▸ beside the event', 'Rename next to the run'],
        what: 'Type a name or tap a quick one (FP1, Q1, Q3, R1 stint 1, R3 stint 2, Warm-up…). A name you type is kept. The weekend page and its Laps tab have the same Rename.' },
      { name: 'Delete a run', where: ['Weekend', '▸ beside the event', 'Delete next to the run'],
        what: 'Asks once, then deletes the run and its logs. The weekend page and its Laps tab have the same Delete.' },
      { name: 'Set who drove a run', where: ['Weekend', '▸ beside the event', 'the driver line under the run', 'Confirm, Change or Set'],
        what: 'Confirm takes the driver the app recognised from the driving style. Change or Set opens the list of drivers; + New driver adds one.' },
      { name: 'Set a run’s tyres', where: ['Weekend', '▸ beside the event', 'the tyres tag (New, Fresh, Used, Very used)'],
        what: 'Tap the tag, then the level. A guess ends with “?” until you pick. Fresh is under 10 laps, Used 10 or more, Very used 25 or more. Laps are compared only with laps on the same tyres.' },
      { name: 'Plan an event', where: ['Weekend', '+ New event'],
        what: 'Name, first and last day and venue. Logs recorded there on those days go into it when you upload them.' },
      { name: 'Rename or delete an event from the list', where: ['Weekend', '▸ beside the event', 'Rename or Delete'],
        what: 'The same as on the event’s page: Delete asks what to delete.' },
      { name: 'Runs in no event', where: ['Weekend', 'Unfiled'],
        what: 'Runs that are in no event. Open it to tick runs and move them into an event, or delete them.' },
      { name: 'Answer which season an upload belongs to', where: ['Weekend', '+ N questions about seasons'],
        what: 'Shows only when the app isn’t sure; one tap answers each question.' },
    ],
  },
  {
    key: 'event',
    title: 'The weekend page',
    dek: 'One event: Laps, Before, During and After, its runs, results and everything worked out from them.',
    items: [
      { name: 'Race weekend or coaching day', where: ['the event', 'Race weekend / Coaching day at the top'],
        what: 'Switches the event between a race weekend and a coaching day with a client. A coaching day shows the three things to improve, whether they were fixed and corner by corner, and is listed under Coaching.' },
      { name: 'Suggested comparisons', where: ['the event', 'Laps', '01 Suggested comparisons'],
        what: 'The comparisons worth making, worked out for you: teammates head to head, each driver against their last session, the best lap against a typical one, like with like on tyres. Each says the corners where most of the gap is and what went wrong there. Tap one to see it below.' },
      { name: 'Pick your own laps to compare', where: ['the event', 'Laps', '06 Pick your own laps'],
        what: 'Tick two to six laps from any run, then Compare. Each run’s best lap is on purple; laps that aren’t clean are grey, and each lap’s type is written under it (Clean, Out, Build, In, Slow): tap it to change it. Each run has its driver, tyres, Rename and Delete too.' },
      { name: 'Prep report before the weekend', where: ['the event', 'Before'],
        what: 'Also Prep report on Weekend, under an upcoming event. What past events at this track learned: the lap time to aim for, the gear map, corner by corner with what the top 10% do, track grip, quali prep that worked, tyre pressures, setups and how the car behaved, and each driver’s recurring mistakes. Year by year, official results and the prediction are folded at the end.' },
      { name: 'Every lap of a session', where: ['the event', 'During', '01 every lap', 'Session'],
        what: 'Opens on every lap of the latest session. Pick another session, or Add runs from other sessions. Tap a lap to put it on the traces (up to 6) or take it off. A green flag names the corners where a lap holds the session’s best.' },
      { name: 'Best in each corner', where: ['the event', 'During', '02 Best in each corner'],
        what: 'The quickest pass of each corner in the session and which lap it was. Add puts it on the traces.' },
      { name: 'Stint and combined theoretical', where: ['the event', 'During', 'Theoretical laps'],
        what: 'A stint theoretical for each stint and one combined theoretical, built from the best sections. Add to graph draws them dashed. They are not real laps.' },
      { name: 'Three things for next run', where: ['the event', 'During', 'Three things for next run'],
        what: 'For each driver’s latest run, the costliest repeated mistakes and what each is worth.' },
      { name: 'Session reports', where: ['the event', 'During or After', 'Session reports', 'Report'],
        what: 'One report for each official session (FP1, Q1, R1…).' },
      { name: 'Debriefs of the weekend', where: ['the event', 'During', 'Debriefs'],
        what: 'Record debrief for the latest run, and for each run whether it has one: Read opens it, Record records one for that run.' },
      { name: 'The whole event’s report', where: ['the event', 'After'],
        what: 'Session reports, the runs, side by side, the full event report and the official results.' },
      { name: 'Runs side by side', where: ['the event', 'During or After', 'Runs', 'tick two to six runs'],
        what: 'A table of lap times, consistency, best section times, top speed, tyres and conditions, a column per run. Compare laps at the foot of the screen opens their best laps on Compare laps.' },
      { name: 'Rename a run in place', where: ['the event', 'During or After', 'Runs', 'tap the run’s name, or Rename'],
        what: 'Opens the name’s editor under the run, with the quick names.' },
      { name: 'Move runs to another event', where: ['the event', 'Runs', 'tick the runs', 'Move…'],
        what: 'Into another event, out of this one, or into a new event. The reports of both events are worked out again.' },
      { name: 'Delete several runs', where: ['the event', 'Runs', 'tick the runs', 'Delete…'],
        what: 'Asks once, says how much space it frees, then deletes the runs and their logs.' },
      { name: 'Official results', where: ['the event', 'During or After', 'Results', 'Get results'],
        what: 'Fetches the official results sheets, a column per session. Change sets which car number is ours.' },
      { name: 'Which session a run was', where: ['the event', 'under the tabs'],
        what: 'When the app isn’t sure which session a log was (FP1, Q2…), it asks here with one-tap answers.' },
      { name: 'Rename the event or change its dates', where: ['the event', 'More at the foot', 'Rename or Change dates'],
        what: 'Leave the dates empty to take them from the logs.' },
      { name: 'Delete logs or the event', where: ['the event', 'More at the foot', 'Delete logs or event'],
        what: 'Asks what to delete: only the logs and keep the event (ready for the right logs), the whole event, only the event and keep its runs, or nothing.' },
      { name: 'The event’s analyses', where: ['the event', 'More at the foot'],
        what: 'Full report, Technique check, Quali prep, Stint analysis, Compare drivers, Driver fingerprints, Prediction and Predicted vs actual for this event.' },
    ],
  },
  {
    key: 'run',
    title: 'A run',
    dek: 'One run’s page: its lap chart, every lap, the track, corner by corner and its setup.',
    items: [
      { name: 'Open a run', where: ['the event', 'tap a run’s best lap'],
        what: 'Or tap the run on Weekend. The runs of the event are listed at the top to switch to another.' },
      { name: 'Lap chart', where: ['a run', '02 Lap chart'],
        what: 'Every lap with its type, time, gap, section times, hot tyre pressures and tyre temperatures. Best of this run and of the event are at the foot.' },
      { name: 'Change a lap’s type', where: ['a run', 'Lap chart', 'tap the lap’s type (Clean, Out, In…)'],
        what: 'Set Out lap, Build lap, Push lap or In lap when the app read it wrong; Let the app read it undoes it. Your pick shows a dot and wins on every page, even after the log is read again. The word under each lap on the Laps tab does the same.' },
      { name: 'Compare laps of a run', where: ['a run', 'Lap chart', 'tick laps', 'Compare laps'],
        what: 'Tick two to six laps. With one ticked, it compares it against the fastest.' },
      { name: 'Corner by corner and lap against lap', where: ['a run', 'Corner by corner, Lap against lap'],
        what: 'Each corner’s apex, braking, minimum speed and full throttle on the lap against the best, then any lap against the reference lap, trace on trace.' },
      { name: 'Setup of a run', where: ['a run', 'The car', 'Setup sheet or Copy from the previous run'],
        what: 'What was changed on the car for this run, on the car’s setup sheet.' },
      { name: 'Add a log to a run', where: ['a run', 'Upload a logger file'],
        what: 'A MoTeC .ld (with its .ldx) or a CSV export.' },
      { name: 'From a run to its analyses', where: ['a run', 'the links at the top'],
        what: 'Report: how to go faster, Technique check, Racing line 3D, Quali prep, Stint analysis and Compare.' },
    ],
  },
  {
    key: 'debriefs',
    title: 'Debriefs',
    dek: 'What the driver says after a run, written down and checked against the data.',
    href: '/debrief',
    items: [
      { name: 'Record a debrief', where: ['Debrief (the red square on any page)'],
        what: 'Recording starts at once. Pause and Carry on recording make one debrief in parts; Stop and send sends it; Delete throws it away before it is sent.' },
      { name: 'Pick the run, who talks and the language', where: ['Debrief', 'More options'],
        what: 'Session: the last run by time or one of the newest runs. One driver or Group. English, Italiano, Deutsch or Mixed (the default, for a mix of languages).' },
      { name: 'Upload a voice note', where: ['Debrief', 'More options', 'Upload a recording instead'],
        what: 'Any audio file, WhatsApp voice notes too.' },
      { name: 'Type a debrief', where: ['Debrief', 'More options', 'Type points by hand'],
        what: 'Pick the run and the topic (car balance, tyres, brakes…), write the point, Add point, then Save debrief.' },
      { name: 'Recordings waiting for their run', where: ['Debrief', 'More options', 'Waiting for their run'],
        what: 'Recordings made before their run’s log was uploaded. They join their run by themselves after the upload, or pick it here.' },
      { name: 'Read a debrief', where: ['the event', 'During', 'Debriefs', 'Read'],
        what: 'The summary, then every point checked against the data: Matches, Partly matches, Data doesn’t show it, Data says the opposite. ▶ plays the recording from that moment; What it means says what to try.' },
      { name: 'Change which run a debrief goes with', where: ['a debrief', 'Change run'],
        what: 'Pick its run. A debrief matched by time says so, with Confirm and Change.' },
      { name: 'Setup changes between stints', where: ['a debrief', 'Change stints'],
        what: 'One debrief covers its session’s stints. Mark which stints ran which setup, or leave one out.' },
      { name: 'Fix the transcript', where: ['a debrief', 'Show transcript', 'Edit transcript', 'Save and sort again'],
        what: 'Correct the words; the points are sorted again from your text.' },
      { name: 'Transcribe again', where: ['a debrief', 'Transcribe again'],
        what: 'Listens to the recording again for Italian, English and German. It replaces your edits.' },
      { name: 'Share a debrief', where: ['a debrief', 'Share'],
        what: 'The phone’s share sheet, or Send by WhatsApp, Send by email and Copy text.' },
      { name: 'Delete a debrief', where: ['a debrief', 'Delete debrief'],
        what: 'Deletes the debrief and its recording, after one confirm.' },
      { name: 'From Debrief to the data', where: ['Debrief on a phone', 'Go to data'],
        what: 'Opens the weekend that is on, or the next one.' },
    ],
  },
  {
    key: 'upload',
    title: 'Upload',
    dek: 'Logs in: MoTeC .ld with .ldx, CSV exports, zips of a whole test or weekend, whole folders.',
    href: '/upload',
    items: [
      { name: 'Upload logs', where: ['Upload', 'drop or pick the files'],
        what: 'Each zip or folder becomes an event named after it. Logs from a planned event’s track and days go into that event; loose logs go to Unfiled. If the connection drops, the files are sent again by themselves.' },
      { name: 'Tyres after an upload', where: ['Upload', 'Tyres for each stint'],
        what: 'The app’s guess for each stint is ticked: Confirm all, or tap the right level.' },
      { name: 'Put an upload into an event you have', where: ['Upload', 'New event from …', 'Put its runs in'],
        what: 'When it is the same race weekend as an event you have. Otherwise name the new event, then Open it.' },
    ],
  },
  {
    key: 'reports',
    title: 'Reports',
    dek: 'How to go faster: for the whole event, one session or one run, like with like on tyres.',
    items: [
      { name: 'Open a report', where: ['the event', 'After', 'More at the foot', 'Full report'],
        what: 'Or Report on a session in During or After, or Report: how to go faster on a run.' },
      { name: 'Pick what a report covers', where: ['a report', 'Report for', 'Whole event, a session or a run'],
        what: 'The same report for the whole event, one official session or one run.' },
      { name: 'Like with like on tyres', where: ['a report', 'New, Fresh, Used, Very used tyres'],
        what: 'Each lap is compared only with laps on the same tyres. The level with most laps opens first.' },
      { name: 'Pick the laps a report uses', where: ['a report (whole event)', 'Pick the laps to compare', 'Tyres, Session, Driver'],
        what: 'The report is worked out again for just those runs a second after your last tap.' },
      { name: 'Top three gains', where: ['a report', 'Top three gains'],
        what: 'The three places with most time to find. Tap one to see it on the map.' },
      { name: 'Corner by corner, in plain words', where: ['a report', 'Corner by corner'],
        what: 'For each tyre level, the quickest pass of each corner against the typical pass, biggest gain first, with what was done differently (“braking earlier into T1 is faster”) and what it is worth.' },
      { name: 'Grip use and traction control', where: ['a report', 'Grip use & traction control'],
        what: 'How much of the grip each phase uses on the quick laps against the slow ones, and where it is left unused. Traction control: each zone where it cut in, what it cost and a verdict (Costs time, Small loss, Sign of pushing, No effect), with the TC level on the dash (a higher number cuts in earlier and more). On the M4 GT4 Evo it says where the TC override button is worth it.' },
      { name: 'Car balance', where: ['a report', 'Car balance'],
        what: 'Understeer or oversteer on entry, mid-corner and exit for each section, on all clean laps or the top 10%. Data only: setup changes are in the Setup tool.' },
      { name: 'Compare stints in a report', where: ['a report', 'Compare stints'],
        what: 'Two or more stints side by side.' },
    ],
  },
  {
    key: 'compare',
    title: 'Compare laps',
    dek: 'Two to six real laps from any sessions at one track, trace on trace.',
    href: '/compare',
    items: [
      { name: 'Compare two to six laps', where: ['the event', 'tick runs or laps', 'Compare laps'],
        what: 'The laps, where the time is (the top three sections lost), best in each corner, section times, theoretical laps and the traces.' },
      { name: 'Add a lap from another session', where: ['Compare laps', '+ Add a lap from another session'],
        what: 'Tap Add on a session for its best lap, again for the next best. One track at a time; ✕ removes a lap.' },
      { name: 'Zoom the traces', where: ['Compare laps', 'Traces'],
        what: 'Pinch or scroll to zoom, or drag a box with the mouse; double-tap or double-click goes back. Zoom jumps to a section. Every graph in the app zooms the same way.' },
    ],
  },
  {
    key: 'analyses',
    title: 'Technique, stints and quali',
    dek: 'The checks worked out from the laps of an event or a run.',
    items: [
      { name: 'Technique check', where: ['the event', 'More at the foot', 'Technique check'],
        what: 'Or from a run, or Technique check, every corner in During. Every clean lap checked for obvious mistakes: lifting on exit, speed stalling, throttle on and off, braking grip unused, an early or late upshift, oversteer on the power. Each with its corner, what it cost and what to do instead, then the lap without its mistakes and the mistakes that repeat.' },
      { name: 'See a mistake on the traces', where: ['Technique check', 'tap a mistake', 'On the track'],
        what: 'The close-up of speed, throttle, brake, steering, gear, revs, rear wheelspin and traction control (TC) where it happened, with the best real passes laid over it dashed.' },
      { name: 'Correct a lap’s type or tyres in the check', where: ['Technique check', 'Change lap type, or the Tyres line'],
        what: 'Out, build, push or in lap, and New, Fresh, Used or Very used tyres. The check runs again with them.' },
      { name: 'Racing line in 3D', where: ['a run', 'Racing line, 3D'],
        what: 'Up to four laps driven in 3D in the browser, at the same place or in real time, from the Chase, Above, Trackside or Bird view; then corner by corner: brake point, turn-in, apex, throttle and the slowest point.' },
      { name: 'Stint analysis', where: ['the event', 'More at the foot', 'Stint analysis'], href: '/tools/stint',
        what: 'How the car fades over a stint with fuel and tyres apart, grip and balance per phase, and how the driver adapts. Tag laps lost to a safety car, FCY or traffic (SC, FCY, Traffic) and they leave the trends.' },
      { name: 'Compare stints: did a setup change work?', where: ['Stint analysis', 'Compare stints'],
        what: 'Before and after the change: what changed on the car (from the setup sheets), like-with-like checks, lap times, grip and balance by phase, the corners where the balance moved, tyres and driver aids. Reports have it too.' },
      { name: 'Quali prep', where: ['the event', 'More at the foot', 'Quali prep'],
        what: 'The plan, warm-up and build laps, when the tyres are ready, tyre windows and long runs, from the tyre pressure sensors. Also from a run.' },
      { name: 'Prediction and predicted vs actual', where: ['the event', 'More at the foot', 'Prediction'],
        what: 'Where our car should qualify and finish, and once the results are in, how close it was. Change sets which car number is ours.' },
    ],
  },
  {
    key: 'coaching',
    title: 'Coaching days',
    dek: 'Days with clients: what to improve, whether it was fixed and where the time goes.',
    href: '/coaching',
    items: [
      { name: 'Make an event a coaching day', where: ['the event', 'Coaching day at the top'],
        what: 'It is then listed under Coaching, newest first, and opens on the coaching view.' },
      { name: 'Three things to improve', where: ['Coaching', 'the day', '01 Three things to improve'],
        what: 'For each driver’s latest run, the costliest repeated mistakes, one per corner, what to do instead and what each is worth. Pick laps chooses the laps compared.' },
      { name: 'Did we fix it?', where: ['Coaching', 'the day', '02 Did we fix it?'],
        what: 'The last run’s three things checked on the latest run: fixed, better or not yet, and the time gained.' },
      { name: 'Corner time loss for a client', where: ['Coaching', 'the day', '03 Corner by corner'],
        what: 'Each driver’s best lap against the day’s quickest lap, the costliest corners first.' },
      { name: 'Debriefs on a coaching day', where: ['Coaching', 'the day', '04 Debriefs'],
        what: 'Folded: tap it to read or record one.' },
    ],
  },
  {
    key: 'drivers',
    title: 'Drivers',
    dek: 'How each driver drives, their habits, and drivers against each other.',
    href: '/drivers',
    items: [
      { name: 'A driver’s fingerprint', where: ['Drivers'],
        what: 'For each driver: the clearest traits of their driving style, where they have time to gain and their strengths, the events it was learned at with the gap to their teammates, and their habits.' },
      { name: 'Runs put on the wrong driver', where: ['Drivers', 'Not them?'],
        what: 'Pick or type the right driver: every run in that driving style is put on them, and the fingerprint learns it.' },
      { name: 'Tag drivers on many runs at once', where: ['Drivers', 'Tag drivers'], href: '/drivers/tag',
        what: 'Pick the driver, tick the runs (Tick all for an event or a day), then Set.' },
      { name: 'Compare two drivers over all their laps', where: ['Drivers', 'Compare drivers'], href: '/drivers/compare',
        what: 'Two drivers, or two groups of sessions, at one track and car: the typical lap, where the time goes section by section, each section’s technique and habits, and the traces.' },
      { name: 'Drivers corner by corner, same tyres', where: ['the event', 'After', 'More at the foot', 'Full report', 'Drivers'],
        what: 'Two drivers corner by corner: how each brakes, turns and gets back on the throttle, drawn as their Top 10%, Median or Bottom 10% passes, the balance per phase, and lap times corrected to one tyre age and fuel load. On the same tyres, or All to compare whatever the tyres.' },
      { name: 'Driver fingerprints in full', where: ['Tools', 'Driver fingerprints'], href: '/drivers/fingerprints',
        what: 'Every trait, what goes with quicker laps over all the data, and driving styles still waiting for a name: This is… names them.' },
      { name: 'Driver habits over time', where: ['Tools', 'Driver habits'], href: '/drivers/habits',
        what: 'Each driver’s recurring technique mistakes over every event, getting better or worse, beside a teammate’s. Tap a habit for event by event.' },
    ],
  },
  {
    key: 'setup',
    title: 'Setup tool',
    dek: 'Tell it what the car does; it proposes one change at a time and remembers what you can’t change.',
    href: '/setup',
    items: [
      { name: 'Fix a handling problem', where: ['Setup', 'pick the event', 'tap the problem, or type it'],
        what: 'Understeer mid-corner, Oversteer on exit, Locking the fronts… or in your words (“understeer mid-corner in T6”). It proposes one change with why, what to expect and what to watch.' },
      { name: 'Answer a proposal', where: ['Setup', 'Trying it next run, Tried it, it helped, Tried it, no better, Already…'],
        what: 'Each answer moves it to the next change for the same problem. “Already on the softest rear bar” and the like are kept as the event’s limits.' },
      { name: 'Clear a limit', where: ['Setup', 'Can’t go further at this event', 'Clear'],
        what: 'Takes a remembered limit off for this event.' },
      { name: 'Let it read a run', where: ['Setup', 'Run it reads'],
        what: 'The run’s debrief, logger data and setup sheet go into each proposal. Pick none to go on what you tell it.' },
      { name: 'Log the run’s setup', where: ['Setup', 'This run’s setup', 'Same as the previous run, or Log what changed'],
        what: 'A change you are trying is logged on the next run’s sheet when its logs come in, and you are told what it did.' },
      { name: 'Start the conversation again', where: ['Setup', 'Start again'],
        what: 'Clears the conversation for this event.' },
    ],
  },
  {
    key: 'tools',
    title: 'Tools',
    dek: 'Tyres, setup sheets, the car, seasons and the calendar.',
    href: '/tools',
    items: [
      { name: 'Setup sheets', where: ['Tools', 'Setup'], href: '/tools/setup',
        what: 'A setup sheet for each run on the M4 GT4 Evo template, Copy from the previous run, every run against its results, and suggestions from the driver’s words and the data. Not the Setup tool in the top bar.' },
      { name: 'Pressure calculator', where: ['Tools', 'Pressure calculator'], href: '/tools/pressures',
        what: 'The cold pressures to set for today’s temperatures to reach the hot target, from the gas law and from your own logged runs.' },
      { name: 'Tyre temperatures', where: ['Tools', 'Tyre temperatures'], href: '/tools/tyre-temps',
        what: 'Type, paste or read the inside, middle and outside temperatures: camber and pressure advice for each tyre.' },
      { name: 'Tyre fit', where: ['Tools', 'Tyre fit'], href: '/tools/tyre-fit',
        what: 'A tyre’s grip curves fitted from the logs: where grip peaks for hot pressure, temperature and laps on the tyre.' },
      { name: 'Vehicle model', where: ['Tools', 'Vehicle model'], href: '/tools/vehicle',
        what: 'Ride frequencies, roll stiffness and load transfer from the springs and bars, and What if for a bar or spring change.' },
      { name: 'Cars, drivers and teams', where: ['Tools', 'Cars, drivers and teams'], href: '/garage',
        what: 'Cars with their number, model and loggers; drivers, teams, vehicles, and tyres with their P-Book pressures.' },
      { name: 'Seasons', where: ['Tools', 'Seasons'], href: '/seasons',
        what: 'Each championship season: our entry, its rounds as planned events and their entry lists. Update from the series’ site brings in changes.' },
      { name: 'Racing calendar', where: ['Tools', 'Racing calendar'], href: '/tools/calendar',
        what: 'Connect a Google Calendar by its secret iCal address, then pick which entries are events in the app.' },
      { name: 'Light or dark', where: ['Tools', 'Appearance', 'System, Light or Dark'],
        what: 'How the app looks. System follows the phone or computer.' },
    ],
  },
];

const fold = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();

const wordsOf = (s: string) => fold(s).match(/[\p{L}\p{N}%+]+/gu) ?? [];

/** The parts with the functions that have every word typed at the start of one of theirs ("tc" finds TC, not
 * "switch"; any case, any accents, any order); a part found by its own name keeps all its functions. No words: every
 * part. */
export function findInManual(parts: ManualPart[], query: string): ManualPart[] {
  const words = wordsOf(query);
  if (words.length === 0) return parts;
  const has = (text: string) => {
    const own = wordsOf(text);
    return words.every((w) => own.some((o) => o.startsWith(w)));
  };
  return parts.flatMap((p) => {
    if (has(p.title)) return [p];
    const items = p.items.filter((i) => has([p.title, i.name, ...i.where, i.what].join(' ')));
    return items.length ? [{ ...p, items }] : [];
  });
}
