// Generated by scripts/track-photos.mjs from tracks.json: do not edit by hand, run the script again.
// One photo per venue key (lib/venues.ts venueKey), plus "default" for a venue without one.
import { ImageSourcePropType } from 'react-native';

export type TrackPhotoEntry = {
  source: ImageSourcePropType;
  width: number;
  height: number;
  credit: string;
  licence: string;
  link: string;
};

export const TRACK_PHOTOS: Record<string, TrackPhotoEntry> = {
  "default": {
    source: require('../assets/images/tracks/default.jpg'),
    width: 1600,
    height: 1067,
    credit: "Photo: Dimitrios Savva and Jarod Guest via Poly Haven / Wikimedia Commons, CC0",
    licence: "CC0",
    link: "https://commons.wikimedia.org/wiki/File:Backplate_%E2%80%93_Zwartkops_Curve_Sunset_(Dimitrios_Savva_and_Jarod_Guest_via_Poly_Haven)_39.jpg",
  },
  "hockenheim": {
    source: require('../assets/images/tracks/hockenheim.jpg'),
    width: 1600,
    height: 1067,
    credit: "Photo: Kmtextor / Wikimedia Commons, CC BY-SA 4.0, cropped",
    licence: "CC BY-SA 4.0",
    link: "https://commons.wikimedia.org/wiki/File:Hockenheimring_start-ziel-gerade_2010.jpg",
  },
  "zandvoort": {
    source: require('../assets/images/tracks/zandvoort.jpg'),
    width: 1600,
    height: 1066,
    credit: "Photo: dronepicr / Wikimedia Commons, CC BY 2.0",
    licence: "CC BY 2.0",
    link: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Motorsport_race_track_Circuit_Zandvoort_Formula_one_(40889997713).jpg",
  },
};
