#!/usr/bin/env node
// Makes the app's track photos from the photo list (tracks.json: one entry per venue key, plus "default"):
// each photo resized to at most 1600 px wide and compressed under about 300 KB into assets/images/tracks/<key>.jpg,
// then constants/trackPhotos.ts written with each key's image, size, credit, licence and source page.
// Adding a track is adding its entry and photo to tracks.json and running this again.
//
//   node scripts/track-photos.mjs [path/to/tracks.json]
//
// The photos are read from the folder tracks.json is in. Needs ImageMagick (`magick`, or `convert` and `identify`).
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LIST = resolve(process.argv[2] ?? '/mnt/project-files/app/looks/photos/tracks.json');
const OUT_DIR = join(APP, 'assets/images/tracks');
const OUT_TS = join(APP, 'constants/trackPhotos.ts');
const MAX_W = 1600;
const MAX_BYTES = 300 * 1024;

function tool() {
  for (const t of [['magick'], ['convert']]) {
    try {
      execFileSync(t[0], ['-version'], { stdio: 'ignore' });
      return t[0] === 'magick' ? { convert: ['magick'], identify: ['magick', 'identify'] }
        : { convert: ['convert'], identify: ['identify'] };
    } catch {
      // try the next name
    }
  }
  throw new Error('ImageMagick not found: install it (magick, or convert and identify) and run this again.');
}

const im = tool();
const run = (cmd, args) => execFileSync(cmd[0], [...cmd.slice(1), ...args], { encoding: 'utf8' });
const size = (file) => run(im.identify, ['-format', '%w %h', file]).trim().split(' ').map(Number);

const list = JSON.parse(readFileSync(LIST, 'utf8'));
const keys = Object.keys(list).filter((k) => !k.startsWith('_')).sort((a, b) => (a === 'default' ? -1 : b === 'default' ? 1
  : a.localeCompare(b)));
if (!keys.includes('default')) throw new Error(`${LIST} has no "default" entry`);

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });
const rows = [];
for (const key of keys) {
  const e = list[key];
  const src = join(dirname(LIST), e.file);
  const out = join(OUT_DIR, `${key}.jpg`);
  // the largest quality that keeps it under the size
  let quality = 84;
  for (;;) {
    run(im.convert, [src, '-auto-orient', '-resize', `${MAX_W}x>`, '-strip', '-interlace', 'Plane', '-sampling-factor',
      '4:2:0', '-quality', String(quality), out]);
    if (statSync(out).size <= MAX_BYTES || quality <= 50) break;
    quality -= 4;
  }
  const [w, h] = size(out);
  // a CC BY-SA photo is shown cropped to fill its frame: a changed work, so its credit says so
  const credit = /BY-SA/i.test(e.licence ?? e.credit) && !/cropped/i.test(e.credit) ? `${e.credit}, cropped` : e.credit;
  rows.push({ key, w, h, credit, licence: e.licence, source: e.source });
  console.log(`${key}: ${w}x${h}, ${Math.round(statSync(out).size / 1024)} KB at quality ${quality}`);
}

const q = (s) => JSON.stringify(s);
writeFileSync(OUT_TS, `// Generated by scripts/track-photos.mjs from tracks.json: do not edit by hand, run the script again.
// One photo per venue key (lib/venues.ts venueKey), plus "default" for a venue without one.
import { ImageSourcePropType } from 'react-native';

export type TrackPhotoEntry = {
  source: ImageSourcePropType;
  width: number;
  height: number;
  credit: string;
  licence: string;
  link: string;
};

export const TRACK_PHOTOS: Record<string, TrackPhotoEntry> = {
${rows.map((r) => `  ${q(r.key)}: {
    source: require('../assets/images/tracks/${r.key}.jpg'),
    width: ${r.w},
    height: ${r.h},
    credit: ${q(r.credit)},
    licence: ${q(r.licence)},
    link: ${q(r.source)},
  },`).join('\n')}
};
`);
console.log(`wrote ${OUT_TS}`);
